name: Backend CI/CD

on:
  push:
    paths:
      - 'be/**'
  pull_request:
    paths:
      - 'be/**'

defaults:
  run:
    working-directory: ./be 

env:
  IMAGE_NAME: expense_api

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: ['20']

    name: Build using Node v${{ matrix.node-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build app
        run: yarn build

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20']

    name: Test using Node v${{ matrix.node-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Test App
        run: yarn test

  publish:
      runs-on: ubuntu-latest
      needs: [build, test]
      name: Publish image 

      steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
      
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: ./be
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          
        # - name: Run the image in a container
        #   uses: addnab/docker-run-action@v3
        #   with:
        #     image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        #     run: |
        #       echo "runing the docker image"
        #       echo "Testing the nodejs app endpoints"
        #       echo ${{ steps.docker_build.outputs.digest }}

  